name: Auto Check & Fix

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Красиво оформим файлы
      - name: Prettier format
        run: npx --yes prettier@3 -w .

      # Починим простые ошибки в JS/TS
      - name: ESLint fix
        run: npx --yes eslint@8.57.0 . --ext .js,.ts,.jsx,.tsx --fix || true

      # Если были правки — робот сам закоммитит их обратно
      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-fix (prettier+eslint)"
          branch: ${{ github.head_ref || github.ref_name }}